<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-WorkerServiceDI-e86cd9c7-6f3c-4271-b764-d030f811ada6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka" Version="1.5.38" />
        <PackageReference Include="Akka.Hosting" Version="1.5.38" />
        <PackageReference Include="Akka.Logger.Serilog" Version="1.5.25" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2"/>
    </ItemGroup>
</Project>
